### ISSUE TITLE
Talks missing?

### ISSUE THREAD

**Issue by qubodup** [PyLadiesBerlin/resources#2]
Hi,

I'm not sure whether or not it might be intended but it looks like the following workshop materials are missing:

Jan 2015 http://www.meetup.com/PyLadies-Berlin/events/219428787/
- not sure if there was any material shared, video is in progress (which would be useless without material though)

Nov 2014 http://www.meetup.com/PyLadies-Berlin/events/215350262/ material:
- https://speakerdeck.com/debilski/pelita-coding-algorithms-to-win-at-pyladies-berlin-2014
- https://www.youtube.com/watch?v=AD1cSBCEUzA

Oct 2014 http://www.meetup.com/PyLadies-Berlin/events/211277902/ material:
- https://github.com/guillermoaguilar/pyglet_tutorial
- https://www.youtube.com/watch?v=wrWwD6DcSIs

**Comment by lluminita** [comment]
I think for Jan 2015 is this : https://github.com/PyLadiesBerlin/materials/tree/master/11_building_a_small_web_app_using_mvc_patterns

**Comment by lluminita** [comment]
PR #3 should fix this.
Thanks @qubodup for pointing this out.
